### ISSUE TITLE
Query Regarding API Keys for Royal Mail Tracking

### ISSUE THREAD

**Issue by grekpg** [elliotjreed/royal-mail-tracking#1]
Hello @elliotjreed,

Firstly, I'd like to thank you for creating and maintaining the Royal Mail Tracking library. It's an excellent resource.

We're using Click & Drop extensively, dispatching thousands of parcels monthly. However, we've encountered an issue where the API keys from Click & Drop aren't functioning correctly with the tracking system. I was wondering if you might have any insight or guidance on where we can procure the correct API keys for tracking?

Is there a specific contact or procedure at Royal Mail that you're aware of for this purpose? We're eager to make use of your library, but this API key hurdle is currently standing in our way.

Any advice or direction you could provide would be immensely helpful.

Thank you in advance for your time and assistance.

**Comment by elliotjreed** [comment]
Hi @grekpg,

I believe the Tracking API needs separate API keys from the Shipping API (https://developer.royalmail.net/start), and that the API subscription will need to be initiated by a Royal Mail account manager if you have one, or by contacting the Business Helpdesk on 08457 950 950 or emailing business.customer.service@royalmail.com.
